### PR TITLE
Change #conversationHeader color to set it off from other content.

### PR DESCRIPTION
**Pull request by ctlajoie**
as discussed in #967

### CODE REVIEW

**Comment by protz** [comment]
Very cool. I don't have my linux machine around with me -- would you 
have a screenshot on Linux to make sure we don't break a platform by 
fixing another one?

**Comment by ctlajoie** [comment]
I certainly made sure not to break my primary environment :)

#### Default GTK (Adwaita)
image

#### Dark theme (FlatStudioDark)
image

**Comment by protz** [comment]
Very cool, thanks :)

**Comment by protz** [comment]
https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ the new version has the fix, and you're mentioned in the release notes. Thanks again, and keep sending the good bugfixes :)

**Pull request merged**
