### PR TITLE
Add new option for "enable quick reply"

### PR DESCRIPTION
**Pull request by zzzeek**
While I appreciate greatly the effort and complexity that I can see went into the "Quick Reply" feature at the bottom of the conversation window,  I'd like to support the case for making this feature optional.  In my case, I prefer having a consistent set of controls for writing replies, in particular that I typically need to write my responses inline, I deal with a lot of code samples and complex reply chains,  and in general I need a lot of window room and very consistent controls.  By disabling "Quick Reply" I get the same "Reply" buttons at the bottom of the last message as that of other messages in the thread without the extra boxes and controls getting in the way.

### CODE REVIEW

**Comment by protz** [comment]
I think you can do that without modifying the code... (see
https://github.com/protz/GMail-Conversation-View/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature).
Did that work for you?

**Comment by zzzeek** [comment]
I suppose I could make that recipe work, though it seems that A. clicking a checkbox is simpler and B. changing the CSS on the outside might break across releases / is inconvenient to remember for new installs?

**Comment by protz** [comment]
Well,
- this is an option that I'll never test in my daily usage, meaning that
it's likely to break and cause extra maintenance trouble for me (I was
basically unable to maintain this addon for five of the past six months, so
I'm weary of adding extra burden on my back)
- I still have the hope of adding a "quick reply" feature to every message
in the conversation one day, meaning that this option would stop to make
sense.

**Comment by zzzeek** [comment]
i guess there's no real way to unit test these kinds of things...javascript...

**Comment by zzzeek** [comment]
okey doke then...the stylish thing works fine :)

**Comment by protz** [comment]
Thanks! :)

**Pull request closed without merging**
